---
dependencies:
  - {role: ansible-apt,             tags: apt }
  - {role: ansible-hostname,        tags: hostname }
  - {role: Stouts.sudo,             tags: sudo }
  - {role: ANXS.openssh,            tags: openssh }
  - {role: knopki.locale,           tags: locale }
  - {role: geerlingguy.gitlab,      tags: gitlab_server }
  - {role: bertvv.bind,             tags: bind }
  - {role: atosatto.minio,          tags: minio }
  - {role: geerlingguy.haproxy,          tags: haproxy }